### ISSUE TITLE
v1.0 release checklist

### ISSUE THREAD

**Issue by GeoBrodas** [GeoBrodas/linksnap#11]
Upcoming features listed in this version release - 
- [ ] Change background on profile
- [ ] Bug fixes
- [ ] Launch Newsletter for every new release
- [ ] Add exclusive links on profile ( _similar features seen in Linktr.ee/ bio.link_ )
